spring:
  shell:
    interactive:
      enabled: true
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    mongodb:
      host: localhost
      port: 0
      database: lib-2
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  storetype: hashmap