spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blog
  mail:
    host: smtp.gmail.com
    port: 587
    username: m63336072@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mongock:
  change-logs-scan-package:
    - org.course.changelog
#  runner-type: applicationrunner
#logging:
#  level:
#    root: debug
blog:
  access-key: keykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeyykeyykeyykeyykeyykeyykey
  refresh-key: refrefrefrefrefrefrefrefrefrefrefrefrefrefrefrefreffrefrefrefrefrefrefrefrefrefre
  card:
    x-scale: 5
    y-scale: 3
  domain: localhost
  email: noreply@simple-blog.org
  moderationStatusList:
    - NEW
    - ACCEPTED
    - DECLINED