spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blog
mongock:
  change-logs-scan-package:
    - org.example.changelog
#  runner-type: applicationrunner
#logging:
#  level:
#    root: debug
blog:
  access-key: keykeykeykeykeykeykeykeykeykeykeykeykeykeykeykeyykeyykeyykeyykeyykeyykey
  refresh-key: refrefrefrefrefrefrefrefrefrefrefrefrefrefrefrefreffrefrefrefrefrefrefrefrefrefre
  card:
    x-scale: 5
    y-scale: 3