spring:
  datasource:
    url: jdbc:postgresql:library
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
app:
  book-page-count: 10
  comment-page-count: 5
