--liquibase formatted sql
--changeset author:1
INSERT INTO roles ("role") VALUES('USER');
INSERT INTO roles ("role") VALUES('ADMIN');
INSERT INTO roles ("role") VALUES('ADMIN_TRAINEE');
INSERT INTO permissions ("permission", role_id) VALUES('BOOK_MANAGE', 2);
INSERT INTO permissions ("permission", role_id) VALUES('BOOK_CREATE', 2);
INSERT INTO permissions ("permission", role_id) VALUES('BOOK_UPDATE', 2);
INSERT INTO permissions ("permission", role_id) VALUES('BOOK_DELETE', 2);
INSERT INTO permissions ("permission", role_id) VALUES('BOOK_MANAGE', 3);
INSERT INTO permissions ("permission", role_id) VALUES('BOOK_CREATE', 3);
INSERT INTO permissions ("permission", role_id) VALUES('BOOK_UPDATE', 3);
insert into authors(name) values ('A1');
insert into authors(name) values ('A2');
insert into authors(name) values ('A3');
insert into authors(name) values ('A4');
insert into genres(name) values ('G1');
insert into genres(name) values ('G2');
insert into genres(name) values ('G3');
insert into genres(name) values ('G4');
insert into genres(name) values ('G5');
insert into users(email, first_name, last_name, password, is_enabled, role_id) values ('u1@mail.ru', 'FN1', 'LN1', '$2y$10$ZQ/FU5PJkCHWGnCkS5MET.3AsTetiG/fS4tmQHQFyUUBNbD7yw2/.', true, 2);
insert into users(email, first_name, last_name, password, is_enabled, role_id) values ('u2@mail.ru', 'FN2', 'LN2', '$2y$10$ZQ/FU5PJkCHWGnCkS5MET.3AsTetiG/fS4tmQHQFyUUBNbD7yw2/.', true, 3);
insert into users(email, first_name, last_name, password, is_enabled, role_id) values ('u3@mail.ru', 'FN3', 'LN3', '$2y$10$ZQ/FU5PJkCHWGnCkS5MET.3AsTetiG/fS4tmQHQFyUUBNbD7yw2/.', true, 1);
insert into users(email, first_name, last_name, password, is_enabled, role_id) values ('u4@mail.ru', 'FN4', 'LN4', '$2y$10$ZQ/FU5PJkCHWGnCkS5MET.3AsTetiG/fS4tmQHQFyUUBNbD7yw2/.', true, 1);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B01', 'D1', now(), 4,0,1,1,0,0,0,1);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B02', 'D1', now(), 4,1,0,0,1,1,4,3.3);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B03', 'D1', now(), 4,0,3,0,0,1,2,2.75);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B04', 'D1', now(), 4,0,1,2,1,0,5,3);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B05', 'D1', now(), 2,0,1,1,0,1,3,3.3);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B06', 'D1', now(), 2,0,0,0,0,0,0,0);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B07', 'D1', now(), 2,0,0,0,0,2,1,5);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B08', 'D1', now(), 2,1,2,0,0,0,0,1.5);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B09', 'D1', now(), 3,0,0,0,0,0,0,0);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B10', 'D1', now(), 3,0,0,0,0,0,0,0);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B11', 'D1', now(), 1,0,0,0,0,0,2,0);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B12', 'D1', now(), 1,0,0,0,0,0,0,0);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B13', 'D1', now(), 1,0,0,0,0,0,0,0);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B14', 'D1', now(), 1,0,0,0,0,0,0,0);
insert into books(title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count, avg_score) values ('B15', 'D1', now(), 1,0,0,0,0,0,0,0);
insert into books_to_genres(book_id, genre_id) values (1, 1);
insert into books_to_genres(book_id, genre_id) values (1, 2);
insert into books_to_genres(book_id, genre_id) values (1, 3);
insert into books_to_genres(book_id, genre_id) values (2, 1);
insert into books_to_genres(book_id, genre_id) values (2, 2);
insert into books_to_genres(book_id, genre_id) values (3, 1);
insert into books_to_genres(book_id, genre_id) values (3, 3);
insert into books_to_genres(book_id, genre_id) values (4, 1);
insert into books_to_genres(book_id, genre_id) values (4, 4);
insert into books_to_genres(book_id, genre_id) values (5, 1);
insert into books_to_genres(book_id, genre_id) values (5, 2);
insert into books_to_genres(book_id, genre_id) values (6, 1);
insert into books_to_genres(book_id, genre_id) values (7, 3);
insert into books_to_genres(book_id, genre_id) values (8, 4);
insert into books_to_genres(book_id, genre_id) values (9, 4);
insert into books_to_genres(book_id, genre_id) values (10, 5);
insert into books_to_genres(book_id, genre_id) values (11, 5);
insert into books_to_genres(book_id, genre_id) values (12, 5);
insert into books_to_genres(book_id, genre_id) values (13, 2);
insert into books_to_genres(book_id, genre_id) values (14, 1);
insert into books_to_genres(book_id, genre_id) values (15, 2);
insert into books_to_genres(book_id, genre_id) values (15, 4);
insert into comments(book_id, user_id, time, text) values(4, 1, now(), 'C1');
insert into comments(book_id, user_id, time, text) values(4, 1, now(), 'C2');
insert into comments(book_id, user_id, time, text) values(4, 2, now(), 'C3');
insert into comments(book_id, user_id, time, text) values(4, 2, now(), 'C4');
insert into comments(book_id, user_id, time, text) values(4, 1, now(), 'C5');
insert into comments(book_id, user_id, time, text) values(2, 1, now(), 'C6');
insert into comments(book_id, user_id, time, text) values(2, 2, now(), 'C7');
insert into comments(book_id, user_id, time, text) values(2, 3, now(), 'C8');
insert into comments(book_id, user_id, time, text) values(2, 2, now(), 'C9');
insert into comments(book_id, user_id, time, text) values(3, 3, now(), 'C10');
insert into comments(book_id, user_id, time, text) values(3, 1, now(), 'C11');
insert into comments(book_id, user_id, time, text) values(7, 1, now(), 'C12');
insert into comments(book_id, user_id, time, text) values(11, 2, now(), 'C13');
insert into comments(book_id, user_id, time, text) values(11, 1, now(), 'C14');
insert into comments(book_id, user_id, time, text) values(5, 1, now(), 'C15');
insert into comments(book_id, user_id, time, text) values(5, 2, now(), 'C16');
insert into comments(book_id, user_id, time, text) values(5, 3, now(), 'C17');
insert into scores(book_id, user_id, score) values(1, 1, 2);
insert into scores(book_id, user_id, score) values(1, 2, 3);
insert into scores(book_id, user_id, score) values(2, 3, 4);
insert into scores(book_id, user_id, score) values(2, 1, 1);
insert into scores(book_id, user_id, score) values(2, 2, 5);
insert into scores(book_id, user_id, score) values(3, 3, 2);
insert into scores(book_id, user_id, score) values(3, 1, 2);
insert into scores(book_id, user_id, score) values(3, 2, 5);
insert into scores(book_id, user_id, score) values(3, 4, 2);
insert into scores(book_id, user_id, score) values(4, 1, 3);
insert into scores(book_id, user_id, score) values(4, 3, 4);
insert into scores(book_id, user_id, score) values(4, 2, 2);
insert into scores(book_id, user_id, score) values(4, 4, 3);
insert into scores(book_id, user_id, score) values(7, 3, 5);
insert into scores(book_id, user_id, score) values(7, 2, 5);
insert into scores(book_id, user_id, score) values(8, 1, 1);
insert into scores(book_id, user_id, score) values(8, 4, 2);
insert into scores(book_id, user_id, score) values(5, 1, 3);
insert into scores(book_id, user_id, score) values(5, 3, 5);
insert into scores(book_id, user_id, score) values(5, 2, 2);