test:
  max-answers-count: 5
  test-question-count: 5
  pass-rate: 50
  locale: de
  csv-file-name: questions/questions.csv

spring:
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: bundle
    encoding: UTF-8
  shell:
    interactive:
      enabled: true