spring:
  data:
    mongodb:
      host: ${mongo_host}
      port: ${mongo_port}
      database: ${mongo_db}
    rest:
      basePath: datarest
  jmx:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: test.log
#  level:
#    root: debug