version: "3"
services:
  library:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - mongo_host=mongo-datasourse
      - mongo_port=27017
      - mongo_db=lib
  mongo-datasourse:
    image: mongo
    ports:
      - 27017:27017