FROM maven:3.8.1-openjdk-11
RUN mkdir -p /opt/tmp/src
COPY ./src /opt/tmp/src
COPY ./pom.xml /opt/tmp
WORKDIR /opt/tmp
RUN mvn package -DskipTests

FROM openjdk:11
RUN mkdir -p /opt/project
WORKDIR /opt/project
COPY --from=0 /opt/tmp/target/homework*.jar /opt/project/compiled-project.jar
EXPOSE 8080
CMD ["java", "-jar", "/opt/project/compiled-project.jar"]