--liquibase formatted sql
--changeset author:2
insert into authors(name) values ('A1');
insert into authors(name) values ('A2');
insert into authors(name) values ('A3');
insert into authors(name) values ('A4');
insert into genres(name) values ('G1');
insert into genres(name) values ('G2');
insert into genres(name) values ('G3');
insert into books(name, author_id) values ('B1', 1);
insert into books(name, author_id) values ('B2', 1);
insert into books(name, author_id) values ('B3', 1);
insert into books(name, author_id) values ('B4', 1);
insert into books(name, author_id) values ('B5', 2);
insert into books(name, author_id) values ('B6', 2);
insert into books(name, author_id) values ('B7', 2);
insert into books(name, author_id) values ('B8', 2);
insert into books(name, author_id) values ('B9', 3);
insert into books(name, author_id) values ('B10', 3);
insert into books(name, author_id) values ('B11', 3);
insert into books(name, author_id) values ('B12', 3);
insert into books(name, author_id) values ('B13', 4);
insert into books(name, author_id) values ('B14', 4);
insert into books(name, author_id) values ('B15', 4);
insert into books(name, author_id) values ('B16', 4);
insert into books(name, author_id) values ('B17', 4);
insert into books(name, author_id) values ('B18', 4);
insert into books_to_genres(book_id, genre_id) values (1, 1);
insert into books_to_genres(book_id, genre_id) values (1, 2);
insert into books_to_genres(book_id, genre_id) values (1, 3);
insert into books_to_genres(book_id, genre_id) values (2, 1);
insert into books_to_genres(book_id, genre_id) values (2, 2);
insert into books_to_genres(book_id, genre_id) values (3, 3);
insert into book_comments(book_id, text) values(1, 'C1');
insert into book_comments(book_id, text) values(1, 'C2');
insert into book_comments(book_id, text) values(1, 'C3');
insert into book_comments(book_id, text) values(1, 'C4');
insert into book_comments(book_id, text) values(2, 'C5');
insert into book_comments(book_id, text) values(3, 'C6');
insert into book_comments(book_id, text) values(3, 'C7');