--liquibase formatted sql
--changeset author:3
insert into authors(name) values ('A1');
insert into authors(name) values ('A2x');
insert into genres(name) values ('G1');
insert into genres(name) values ('G2');
insert into genres(name) values ('G3');
insert into users(name) values ('U1');
insert into users(name) values ('U2');
insert into users(name) values ('U3');
INSERT INTO books (title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count) VALUES('B1','D1',now(), 1, 0, 2, 1, 0, 0, 2);
INSERT INTO books (title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count) VALUES('B2','D2',now(), 1, 0, 2, 0, 0, 1, 1);
INSERT INTO books (title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count) VALUES('B3','D3',now(), 1, 1, 1, 1, 0, 0, 2);
INSERT INTO books (title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count) VALUES('B4x','D4',now(), 2, 2, 0, 1, 0, 0, 0);
INSERT INTO books (title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count) VALUES('B5','D5',now(), 2, 0, 0, 2, 1, 0, 0);
INSERT INTO books (title, description, time, author_id, score_one_count, score_two_count, score_three_count, score_four_count, score_five_count, comment_count) VALUES('B6','D6',now(), 2, 0, 0, 0, 0, 3, 0);
insert into books_to_genres(book_id, genre_id) values (1, 1);
insert into books_to_genres(book_id, genre_id) values (1, 2);
insert into books_to_genres(book_id, genre_id) values (1, 3);
insert into books_to_genres(book_id, genre_id) values (2, 1);
insert into books_to_genres(book_id, genre_id) values (2, 2);
insert into books_to_genres(book_id, genre_id) values (3, 3);
insert into comments(book_id, user_id, text) values(1, 1, 'C1');
insert into comments(book_id, user_id, text) values(1, 1, 'C2');
insert into comments(book_id, user_id, text) values(2, 2, 'C3');
insert into comments(book_id, user_id, text) values(3, 2, 'C4');
insert into comments(book_id, user_id, text) values(3, 3, 'C5');
insert into scores(book_id, user_id, score) values(1, 1, 2);
insert into scores(book_id, user_id, score) values(1, 2, 3);
insert into scores(book_id, user_id, score) values(1, 3, 2);
insert into scores(book_id, user_id, score) values(2, 1, 2);
insert into scores(book_id, user_id, score) values(2, 2, 5);
insert into scores(book_id, user_id, score) values(2, 3, 2);
insert into scores(book_id, user_id, score) values(3, 1, 2);
insert into scores(book_id, user_id, score) values(3, 2, 3);
insert into scores(book_id, user_id, score) values(3, 3, 1);
insert into scores(book_id, user_id, score) values(4, 2, 3);
insert into scores(book_id, user_id, score) values(4, 3, 1);
insert into scores(book_id, user_id, score) values(4, 3, 1);
insert into scores(book_id, user_id, score) values(5, 2, 3);
insert into scores(book_id, user_id, score) values(5, 3, 3);
insert into scores(book_id, user_id, score) values(5, 3, 4);
insert into scores(book_id, user_id, score) values(6, 2, 5);
insert into scores(book_id, user_id, score) values(6, 3, 5);
insert into scores(book_id, user_id, score) values(6, 3, 5);